--- #YAML:1.0
name:               DBIx-Class-Graph
version:            0.03
abstract:           Represent a graph in a relational database using DBIC
author:
    - Moritz Onken <onken@houseofdesign.de>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Class::Accessor:  0
    Class::C3:        0
    DBD::SQLite:      0
    DBIx::Class:      0.08
    Graph:            0.89
    List::MoreUtils:  0
    SQL::Translator:  0.08
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
